# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "changjinhan"
repo_name: "ADD-arxiv-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 20

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/add-arxiv-daily.json'
json_gitpage_path: './docs/add-arxiv-daily-web.json'
json_wechat_path: './docs/add-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "ADD":
        filters: ["ADD", "Audio Deepfake Detection", "Deepfake Speech Detection", "Deepfake Speech", "Audio Anti Spoofing", "Automatic Speaker Verification"]


